services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: bella009
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Littleboy1#
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-your-username.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: NODE_ENV
        value: production
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
